package k6gen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vhPedroGitHub/tya/pkg/configyml"

	"go.uber.org/zap"
)

// FlowScript represents a generated k6 script for a single flow.
type FlowScript struct {
	FlowName string
	FileName string
	Content  string
}

// GenerateAll produces k6 JavaScript scripts for every flow in the config.
// It returns one FlowScript per flow plus a run-all.js orchestrator.
func GenerateAll(log *zap.Logger, cfg configyml.RunConfig, apiDir string) ([]FlowScript, error) {
	// Build auth map
	authMap := map[string]configyml.AuthProfile{}
	for _, a := range cfg.AuthProfiles {
		authMap[a.Name] = a
	}

	var scripts []FlowScript

	for _, flow := range cfg.Flows {
		log.Info("generating k6 script", zap.String("flow", flow.Name))
		script, err := generateFlowScript(flow, cfg.BaseURL, authMap, apiDir)
		if err != nil {
			return nil, fmt.Errorf("generate script for flow %s: %w", flow.Name, err)
		}
		scripts = append(scripts, script)
	}

	// Generate run-all.js
	runAll, err := generateRunAll(cfg, scripts)
	if err != nil {
		return nil, fmt.Errorf("generate run-all.js: %w", err)
	}
	scripts = append(scripts, runAll)

	return scripts, nil
}

func generateFlowScript(flow configyml.Flow, baseURL string, authMap map[string]configyml.AuthProfile, apiDir string) (FlowScript, error) {
	var b strings.Builder

	auth := authMap[flow.Auth]

	// Header
	b.WriteString("// Generated by TYA — Test Your API\n")
	fmt.Fprintf(&b, "// Flow: %s\n", flow.Name)
	fmt.Fprintf(&b, "// Type: %s\n", flow.Type)
	b.WriteString("// Generated from config-run.yml\n\n")

	// Imports
	b.WriteString(JSMetricsHeader())
	if auth.Type == "basic" {
		b.WriteString(GenerateAuthImport(auth))
	}
	b.WriteString("\n")

	// Helper functions
	b.WriteString(JSHelperFuncs())
	b.WriteString("\n")

	// Load payload pools
	pools := LoadPayloadPools(flow.Steps, apiDir)
	for _, pool := range pools {
		b.WriteString(GeneratePayloadPoolJS(pool))
		b.WriteString("\n")
	}

	// Configuration
	b.WriteString("export const options = {\n")
	b.WriteString("  scenarios: {\n")
	b.WriteString(GenerateScenarioConfig(flow))
	b.WriteString("  },\n")
	b.WriteString("  thresholds: {\n")
	b.WriteString("    'http_req_duration': ['p(95)<2000'],\n")
	b.WriteString("    'tya_errors': ['count<100'],\n")
	b.WriteString("  },\n")
	b.WriteString("};\n\n")

	// Setup function
	b.WriteString("export function setup() {\n")
	b.WriteString("  const baseURL = __ENV.BASE_URL || " + JsString(baseURL) + ";\n")
	// Inject global state from previous flows (written by runk6s into TYA_GLOBAL_STATE env var)
	b.WriteString("  let globalState = {};\n")
	b.WriteString("  if (__ENV.TYA_GLOBAL_STATE) {\n")
	b.WriteString("    try { globalState = JSON.parse(__ENV.TYA_GLOBAL_STATE); } catch(_) {}\n")
	b.WriteString("  }\n")

	if flow.Auth != "" {
		b.WriteString(GenerateAuthSetupWithGlobal(auth, baseURL))
	} else {
		b.WriteString("  return { globalState: globalState };\n")
	}
	b.WriteString("}\n\n")

	// Default VU function
	b.WriteString("export default function(data) {\n")
	b.WriteString("  const baseURL = __ENV.BASE_URL || " + JsString(baseURL) + ";\n")
	b.WriteString("  const auth = data.auth || {};\n")
	b.WriteString("  const ctx = {};\n")
	b.WriteString("  // Copy auth tokens to context\n")
	b.WriteString("  if (data.auth) {\n")
	b.WriteString("    Object.keys(data.auth).forEach(k => { ctx[k] = data.auth[k]; });\n")
	b.WriteString("  }\n")
	b.WriteString("  ctx['_base_url'] = baseURL;\n")
	// Inject global state from previous flows into ctx and data for iterate flows
	b.WriteString("  // Inject global state from previous flows\n")
	b.WriteString("  const globalState = data.globalState || {};\n")
	b.WriteString("  Object.keys(globalState).forEach(flowKey => {\n")
	b.WriteString("    const flowData = globalState[flowKey];\n")
	b.WriteString("    if (flowData && typeof flowData === 'object') {\n")
	b.WriteString("      Object.keys(flowData).forEach(k => {\n")
	b.WriteString("        ctx[flowKey + '.' + k] = flowData[k];\n")
	b.WriteString("        data[flowKey + '.' + k] = flowData[k];\n")
	b.WriteString("      });\n")
	b.WriteString("    }\n")
	b.WriteString("  });\n\n")

	if flow.Type == "iterate" {
		itemVar := flow.ItemVariable
		if itemVar == "" {
			itemVar = "item"
		}
		// For iterate, parse the list source
		parts := strings.SplitN(flow.IterateList, ".", 2)
		if len(parts) == 2 {
			listKey := parts[0] + "." + parts[1]
			b.WriteString(GenerateIterateStepCode(flow.Steps, flow.Name, itemVar, listKey, auth))
		}
	} else {
		for _, step := range flow.Steps {
			b.WriteString(GenerateStepCode(step, flow.Name, auth))
		}
	}

	b.WriteString("\n")
	b.WriteString("  sleep(0.1);\n")
	b.WriteString("}\n")

	return FlowScript{
		FlowName: flow.Name,
		FileName: flow.Name + ".js",
		Content:  b.String(),
	}, nil
}

func generateRunAll(cfg configyml.RunConfig, scripts []FlowScript) (FlowScript, error) {
	var b strings.Builder

	b.WriteString("// Generated by TYA — Test Your API\n")
	b.WriteString("// Run-all orchestrator: executes flows in dependency order\n\n")
	b.WriteString("import http from 'k6/http';\n")
	b.WriteString("import { check, group, sleep } from 'k6';\n\n")

	// Document flow order
	b.WriteString("// Flow execution order (respects depends_on):\n")
	for _, s := range scripts {
		fmt.Fprintf(&b, "//   - %s\n", s.FlowName)
	}
	b.WriteString("\n")

	b.WriteString("export default function() {\n")
	b.WriteString("  console.log('TYA run-all: This script documents the flow execution order.');\n")
	b.WriteString("  console.log('Run each flow script individually with k6 in this order:');\n")
	for _, s := range scripts {
		if s.FlowName != "" {
			fmt.Fprintf(&b, "  console.log('  k6 run %s');\n", s.FileName)
		}
	}
	b.WriteString("}\n")

	return FlowScript{
		FlowName: "",
		FileName: "run-all.js",
		Content:  b.String(),
	}, nil
}

// WriteScripts writes all generated scripts to the output directory.
func WriteScripts(scripts []FlowScript, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	for _, s := range scripts {
		path := filepath.Join(outputDir, s.FileName)
		if err := os.WriteFile(path, []byte(s.Content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	return nil
}

// configFlowEntry is the per-flow entry written to config.json.
type configFlowEntry struct {
	Name      string   `json:"name"`
	Type      string   `json:"type"`
	File      string   `json:"file"`
	DependsOn []string `json:"depends_on"`
	RPS       float64  `json:"rps"`
	Duration  string   `json:"duration"`
}

// configAuthEntry is the per-auth-profile entry written to config.json.
type configAuthEntry struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// configJSON is the top-level structure written to config.json.
type configJSON struct {
	BaseURL      string            `json:"base_url"`
	Flows        []configFlowEntry `json:"flows"`
	AuthProfiles []configAuthEntry `json:"auth_profiles"`
}

// WriteConfigJSON writes a metadata JSON file alongside the scripts so that
// tya runk6s can read flow ordering and dependency information.
func WriteConfigJSON(cfg configyml.RunConfig, outputDir string) error {
	flows := make([]configFlowEntry, 0, len(cfg.Flows))
	for _, f := range cfg.Flows {
		deps := f.DependsOn
		if deps == nil {
			deps = []string{}
		}
		flows = append(flows, configFlowEntry{
			Name:      f.Name,
			Type:      f.Type,
			File:      f.Name + ".js",
			DependsOn: deps,
			RPS:       f.RequestsPerSecond,
			Duration:  f.Duration,
		})
	}

	auths := make([]configAuthEntry, 0, len(cfg.AuthProfiles))
	for _, a := range cfg.AuthProfiles {
		auths = append(auths, configAuthEntry{Name: a.Name, Type: a.Type})
	}

	out := configJSON{
		BaseURL:      cfg.BaseURL,
		Flows:        flows,
		AuthProfiles: auths,
	}

	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config.json: %w", err)
	}

	path := filepath.Join(outputDir, "config.json")
	return os.WriteFile(path, data, 0o644)
}
