package commands

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"go.uber.org/zap"
)

// NewRunK6SCmd returns the cobra command for `tya runk6s`.
func NewRunK6SCmd(log *zap.Logger) *cobra.Command {
	opts := &RunK6SOptions{}

	cmd := &cobra.Command{
		Use:   "runk6s [directory]",
		Short: "Run generated k6 load-test scripts",
		Long: `Executes k6 scripts generated by 'tya genk6' in dependency order.
Each flow script is run as a separate k6 process. Reports are saved to a
reports/ subdirectory.

Examples:
  tya runk6s config-run-k6/
  tya runk6s config-run-k6/ --base-url http://localhost:9090
  tya runk6s config-run-k6/ --env TEST_USER=admin --env TEST_PASS=secret`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			opts.Dir = args[0]
			return runRunK6S(log, opts)
		},
	}

	cmd.Flags().StringVar(&opts.BaseURL, "base-url", "", "override base URL")
	cmd.Flags().StringToStringVar(&opts.Env, "env", nil, "additional environment variables (KEY=VALUE)")

	return cmd
}

// RunK6SOptions holds options for the runk6s command.
type RunK6SOptions struct {
	Dir     string
	BaseURL string
	Env     map[string]string
}

// flowConfig represents a single flow entry from config.json.
type flowConfig struct {
	Name       string   `json:"name"`
	Type       string   `json:"type"`
	File       string   `json:"file"`
	DependsOn  []string `json:"depends_on"`
	RPS        float64  `json:"rps"`
	Duration   string   `json:"duration"`
}

// k6Config represents the config.json written by genk6.
type k6Config struct {
	BaseURL      string        `json:"base_url"`
	Flows        []flowConfig  `json:"flows"`
}

func runRunK6S(log *zap.Logger, opts *RunK6SOptions) error {
	// Check k6 is installed
	if _, err := exec.LookPath("k6"); err != nil {
		return fmt.Errorf("k6 not found in PATH. Install from https://k6.io/docs/get-started/installation/")
	}

	// Load config.json
	configPath := filepath.Join(opts.Dir, "config.json")
	configData, err := os.ReadFile(configPath)
	if err != nil {
		return fmt.Errorf("read config.json: %w", err)
	}
	var cfg k6Config
	if err := json.Unmarshal(configData, &cfg); err != nil {
		return fmt.Errorf("parse config.json: %w", err)
	}

	// Create reports directory
	reportsDir := filepath.Join(opts.Dir, "reports")
	if err := os.MkdirAll(reportsDir, 0o755); err != nil {
		return fmt.Errorf("create reports dir: %w", err)
	}

	// Build execution order using topological sort
	order, err := topologicalSortK6(cfg.Flows)
	if err != nil {
		return fmt.Errorf("sort flows: %w", err)
	}

	baseURL := opts.BaseURL
	if baseURL == "" {
		baseURL = cfg.BaseURL
	}

	log.Info("running k6 scripts",
		zap.String("dir", opts.Dir),
		zap.Int("flows", len(order)),
		zap.String("base_url", baseURL),
	)

	// globalState accumulates values emitted by TYA_GLOBAL: sentinels across flows.
	// Structure: map[flowName]map[key]any for scalar values,
	//            map[flowName]map[key][]any for list values (appended across VU iterations).
	globalScalars := map[string]map[string]any{}
	globalLists := map[string]map[string][]any{}

	// Execute each flow in order
	for _, fc := range order {
		scriptPath := filepath.Join(opts.Dir, fc.File)
		if _, err := os.Stat(scriptPath); os.IsNotExist(err) {
			log.Warn("script not found, skipping", zap.String("file", fc.File))
			continue
		}

		reportPath := filepath.Join(reportsDir, fc.Name+"-summary.json")
		jsonReportPath := filepath.Join(reportsDir, fc.Name+".json")

		log.Info("running flow", zap.String("flow", fc.Name), zap.String("file", fc.File))

		args := []string{
			"run",
			"--log-format", "json",
			"--summary-export", reportPath,
			"--out", "json=" + jsonReportPath,
			"-e", "BASE_URL=" + baseURL,
		}

		// Add extra env vars
		for k, v := range opts.Env {
			args = append(args, "-e", k+"="+v)
		}

		// Pass accumulated global state to this flow
		if len(globalScalars) > 0 || len(globalLists) > 0 {
			// Build the combined globalState object that setup() will parse
			// Shape: { "flow-name": { "key": value, "key_list": [v1, v2, ...] } }
			combined := map[string]map[string]any{}
			for flowName, keys := range globalScalars {
				if combined[flowName] == nil {
					combined[flowName] = map[string]any{}
				}
				for k, v := range keys {
					combined[flowName][k] = v
				}
			}
			for flowName, keys := range globalLists {
				if combined[flowName] == nil {
					combined[flowName] = map[string]any{}
				}
				for k, v := range keys {
					combined[flowName][k] = v
				}
			}
			stateJSON, err := json.Marshal(combined)
			if err == nil {
				args = append(args, "-e", "TYA_GLOBAL_STATE="+string(stateJSON))
			}
		}

		args = append(args, scriptPath)

		cmd := exec.Command("k6", args...)
		// Capture stderr so we can parse TYA_GLOBAL: sentinels (k6 console.log → stderr),
		// while also streaming output to the user's terminal.
		var stderrBuf bytes.Buffer
		cmd.Stdout = os.Stdout
		cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)

		if err := cmd.Run(); err != nil {
			log.Warn("k6 flow had errors", zap.String("flow", fc.Name), zap.Error(err))
			// Continue with next flow even if this one failed
		} else {
			log.Info("flow completed", zap.String("flow", fc.Name))
		}

		// Parse TYA_GLOBAL: sentinels from captured stderr output
		parseGlobalSentinels(stderrBuf.String(), globalScalars, globalLists)
	}

	fmt.Printf("\nReports written to %s/\n", reportsDir)

	return nil
}

// tyaGlobalSentinel is the parsed structure from a TYA_GLOBAL: console.log line.
type tyaGlobalSentinel struct {
	Flow  string `json:"flow"`
	Key   string `json:"key"`
	Value any    `json:"value"`
	List  bool   `json:"list"`
}

// k6LogLine represents a single JSON-formatted k6 log line.
type k6LogLine struct {
	Level  string `json:"level"`
	Msg    string `json:"msg"`
	Source string `json:"source"`
}

// parseGlobalSentinels scans k6 JSON-format log output for lines where msg
// starts with "TYA_GLOBAL: " and accumulates the values into globalScalars
// and globalLists. k6 is invoked with --log-format json so each stderr line is
// a JSON object like {"level":"info","msg":"TYA_GLOBAL: {...}","source":"console"}.
func parseGlobalSentinels(output string, scalars map[string]map[string]any, lists map[string]map[string][]any) {
	const prefix = "TYA_GLOBAL: "
	scanner := bufio.NewScanner(strings.NewReader(output))
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.Contains(line, prefix) {
			continue
		}
		// Parse the outer k6 JSON log envelope
		var logLine k6LogLine
		if err := json.Unmarshal([]byte(line), &logLine); err != nil {
			continue
		}
		if !strings.HasPrefix(logLine.Msg, prefix) {
			continue
		}
		jsonStr := strings.TrimPrefix(logLine.Msg, prefix)
		var s tyaGlobalSentinel
		if err := json.Unmarshal([]byte(jsonStr), &s); err != nil {
			continue
		}
		if s.List {
			if lists[s.Flow] == nil {
				lists[s.Flow] = map[string][]any{}
			}
			lists[s.Flow][s.Key] = append(lists[s.Flow][s.Key], s.Value)
		} else {
			if scalars[s.Flow] == nil {
				scalars[s.Flow] = map[string]any{}
			}
			scalars[s.Flow][s.Key] = s.Value
		}
	}
}

// topologicalSortK6 sorts flows by dependency order using Kahn's algorithm.
func topologicalSortK6(flows []flowConfig) ([]flowConfig, error) {
	flowMap := map[string]flowConfig{}
	for _, f := range flows {
		flowMap[f.Name] = f
	}

	inDegree := map[string]int{}
	dependents := map[string][]string{} // dep → flows that depend on dep

	for _, f := range flows {
		if _, ok := inDegree[f.Name]; !ok {
			inDegree[f.Name] = 0
		}
		for _, dep := range f.DependsOn {
			inDegree[f.Name]++
			dependents[dep] = append(dependents[dep], f.Name)
		}
	}

	// Seed queue with zero-in-degree flows
	var queue []string
	for _, f := range flows {
		if inDegree[f.Name] == 0 {
			queue = append(queue, f.Name)
		}
	}
	sort.Strings(queue) // deterministic order

	var result []flowConfig
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		result = append(result, flowMap[name])

		for _, dep := range dependents[name] {
			inDegree[dep]--
			if inDegree[dep] == 0 {
				queue = append(queue, dep)
				sort.Strings(queue)
			}
		}
	}

	if len(result) != len(flows) {
		return nil, fmt.Errorf("circular dependency detected")
	}

	return result, nil
}
